owner: Analyzee
repo: status

sites:
  - name: Website
    url: https://analyzee.io
    icon: https://raw.githubusercontent.com/Analyzee/status/master/assets/favicon.ico
  - name: API
    url: https://api.analyzee.io
    icon: https://raw.githubusercontent.com/Analyzee/status/master/assets/favicon.ico
  - name: CDN
    url: https://cdn.jsdelivr.net/npm/@analyzee/core@latest
    icon: https://raw.githubusercontent.com/Analyzee/status/master/assets/favicon.ico
assignees:
  - AntonioStipic

i18n:
  footer: Analyzee.io

status-website:
  name: ''
  cname: status.analyzee.io
  logoUrl: https://raw.githubusercontent.com/Analyzee/status/master/assets/logo.png
  favicon: https://raw.githubusercontent.com/Analyzee/status/master/assets/favicon.ico
  navbar:
    - title: Status
      href: /
    - title: Website
      href: https://analyzee.io
