# Change these first
owner: Analyzee # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: Website
    url: https://analyzee.io
  - name: API
    url: https://api.analyzee.io
assignees:
  - AntonioStipic

status-website:
  name: Analyzee Status
  cname: status.analyzee.io
  logoUrl: https://raw.githubusercontent.com/Analyzee/status/master/assets/logo.png
